### Create a new user
POST http://localhost:3000/client/signup
Content-Type: application/json

{   "firstName":"new",
    "lastName":"newnew",
    "username":"new",
    "email": "asasasawewe1@gmail.com",
    "password": "newtest",
    "gender":"femail"

}

###  verifiy account
POST http://localhost:3000/client/verifyAccount
Content-Type: application/json

{
  "verificationId": "",
  "otp": "",
  "isOtp": true
}

### Sign in as an existing user 
POST http://localhost:3000/client/signin
Content-Type: application/json

{
    "email": "asasasawewe1@gmail.com",
    "password": "newtest"
}



### Sign in as an existing user 
POST http://localhost:3000/client/forget-password
Content-Type: application/json

{
    "email": "asasasawewe1@gmail.com",
}


###  verifiy account
POST http://localhost:3000/client/verify-forget-password
Content-Type: application/json

{
  "verificationId": "",
  "otp": "",
  "isOtp": true
}


###  verifiy account
POST http://localhost:3000/client/reset-password
Content-Type: application/json

{
  "verificationId": "",
  "otp": "",
  "password":"",
  "isOtp": true
}


###  verifiy account
POST http://localhost:3000/client/set-password
Content-Type: application/json

{
  "verificationId": "",
  "otp": "",
  "password":"",
  "isOtp": true
}



