### Create a new user
POST http://localhost:3000/client/signup
Content-Type: application/json

{   "firstName":"nati",
    "lastName":"fiker",
    "username":"nati",
    "email": "natnaelfiker226@gmail.com",
    "password": "testpassword",
    "gender":"man"

}

### Sign in as an existing user 
POST http://localhost:3000/client/signin
Content-Type: application/json

{
    "email": "test123@gmail.com",
    "password": "test"
}